name: MCP Daily

on:
  workflow_dispatch:
    inputs:
      dry_run:
        description: "Dry run (no external side-effects)"
        required: false
        type: boolean
        default: false
      assist_mode:
        description: "Assistant mode (extra logs/suggestions)"
        required: false
        type: boolean
        default: true
      PLATFORMS:
        description: "Comma-separated platform keys to run (empty = none)"
        required: false
        type: string
        default: ""
  schedule:
    - cron: "0 7 * * *"

permissions:
  contents: read

jobs:
  mcp_daily:
    name: Run MCP daily
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Prepare env from inputs
        run: |
          echo "DRY_RUN=${{ inputs.dry_run }}" >> $GITHUB_ENV
          echo "ASSIST_MODE=${{ inputs.assist_mode }}" >> $GITHUB_ENV
          echo "PLATFORMS=${{ inputs.PLATFORMS }}" >> $GITHUB_ENV
      - name: Run MCP daily
        run: |
          python -u mcp/main.py
      - name: Upload daily summaries
        uses: actions/upload-artifact@v4
        with:
          name: daily_summaries
          path: daily_summaries/*.json
          if-no-files-found: error

    # NOTE: There are intentionally zero references to APPEN_* or TOLOKA_* secrets.
    # Future adapters can add their own, but default is "no external platforms".
